ARG CONTAINER_IMAGE=my-solution:v1
FROM ${CONTAINER_IMAGE}

ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp
ENV ZENOH_ROUTER_CHECK_ATTEMPTS=-1
ENV AIC_ROUTER_ADDR=zenoh-router.app-intrinsic-base.svc.cluster.local:7447
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/nvidia/bin
