seed: 42

models:
  separate: true
  policy:
    class: GaussianMixin
    clip_actions: true
    clip_log_std: true
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: -2.0
    network:
      - name: net
        input: OBSERVATIONS
        layers: [256, 256, 128]
        activations: elu
    output: tanh(ACTIONS)
  critic_1:
    class: DeterministicMixin
    clip_actions: false
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [256, 256, 128]
        activations: elu
    output: ONE
  critic_2:
    class: DeterministicMixin
    clip_actions: false
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [256, 256, 128]
        activations: elu
    output: ONE
  target_critic_1:
    class: DeterministicMixin
    clip_actions: false
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [256, 256, 128]
        activations: elu
    output: ONE
  target_critic_2:
    class: DeterministicMixin
    clip_actions: false
    network:
      - name: net
        input: concatenate([OBSERVATIONS, ACTIONS])
        layers: [256, 256, 128]
        activations: elu
    output: ONE

memory:
  class: RandomMemory
  memory_size: 4096

agent:
  class: SAC
  gradient_steps: 1
  batch_size: 4096
  discount_factor: 0.99
  polyak: 0.005
  learning_rate: 0.0003
  learning_rate_scheduler: null
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  random_timesteps: 100
  learning_starts: 100
  grad_norm_clip: 1.0
  learn_entropy: true
  initial_entropy_value: 0.15
  target_entropy: -3.0
  rewards_shaper: null
  mixed_precision: true
  experiment:
    directory: logs/skrl/aic_last_inch_sac
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto
    store_separately: false
    wandb: false
    wandb_kwargs: {}

trainer:
  class: SequentialTrainer
  timesteps: 5000000
  environment_info: log
