#!/usr/bin/env python3
"""Train a YOLO pose model for the physical SC front-mouth target.

The input must be the separate ``sc_mouth_pose`` dataset generated by
``DataCollectorScMouthPoseGT``.  It is intentionally incompatible with the
legacy virtual-rectangle SC checkpoint: labels contain four physical mouth
corners and an explicit centre (five keypoints, 20 tokens per object).
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import time


EXPECTED_KEYPOINTS = 5
EXPECTED_LABEL_TOKENS = 5 + 3 * EXPECTED_KEYPOINTS


def _parse_args():
    repo_root = Path(__file__).resolve().parents[3]
    dataset_root = Path.home() / "aic_perception_data" / "sc_mouth_pose"
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=dataset_root / "aic_sc_mouth_pose.yaml")
    parser.add_argument("--model", default="yolo11s-pose.pt")
    parser.add_argument("--epochs", type=int, default=120)
    parser.add_argument("--imgsz", type=int, default=960)
    parser.add_argument("--batch", type=int, default=8)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--project", type=Path, default=dataset_root / "runs")
    parser.add_argument("--name", default="sc_mouth_pose_yolo11s_960")
    parser.add_argument(
        "--final-weights",
        type=Path,
        default=repo_root / "aic_example_policies" / "aic_example_policies" / "ros" / "weights" / "best_sc_mouth_pose.pt",
    )
    parser.add_argument(
        "--metrics-out", type=Path, default=dataset_root / "reports" / "train_sc_mouth_pose.json"
    )
    parser.add_argument("--seed", type=int, default=20260727)
    parser.add_argument("--patience", type=int, default=30)
    parser.add_argument("--resume", action="store_true")
    return parser.parse_args()


def _choose_device(requested: str) -> tuple[str, str]:
    os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")
    import torch

    if requested != "auto":
        return requested, torch.__version__
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return "mps", torch.__version__
    if torch.cuda.is_available():
        return "0", torch.__version__
    return "cpu", torch.__version__


def _dataset_counts(data_yaml: Path) -> dict[str, int]:
    root = data_yaml.parent
    counts: dict[str, int] = {}
    for split in ("train", "val", "test"):
        images = root / "images" / split
        labels = root / "labels" / split
        image_paths = sorted(images.glob("*.png")) if images.is_dir() else []
        counts[f"{split}_images"] = len(image_paths)
        counts[f"{split}_labels"] = sum((labels / f"{path.stem}.txt").is_file() for path in image_paths)
    return counts


def _check_label_shape(data_yaml: Path, *, limit: int | None = None) -> None:
    """Reject mixed legacy/physical conventions before allocating a GPU."""

    root = data_yaml.parent
    for split in ("train", "val", "test"):
        labels = sorted((root / "labels" / split).glob("*.txt"))
        if limit is not None:
            labels = labels[:limit]
        for label in labels:
            for line_number, line in enumerate(label.read_text(encoding="utf-8").splitlines(), start=1):
                tokens = line.split()
                if len(tokens) != EXPECTED_LABEL_TOKENS:
                    raise RuntimeError(
                        f"{label}:{line_number} has {len(tokens)} tokens; expected "
                        f"{EXPECTED_LABEL_TOKENS} for a five-keypoint physical SC mouth"
                    )
                if tokens[0] != "0":
                    raise RuntimeError(f"{label}:{line_number} has unexpected class id {tokens[0]!r}")


def main():
    args = _parse_args()
    data_yaml = args.data.expanduser().resolve()
    if not data_yaml.is_file():
        raise FileNotFoundError(f"dataset YAML not found: {data_yaml}")
    if "kpt_shape: [5, 3]" not in data_yaml.read_text(encoding="utf-8"):
        raise RuntimeError(f"{data_yaml} is not the expected five-keypoint SC-mouth dataset")
    counts = _dataset_counts(data_yaml)
    for split in ("train", "val", "test"):
        if counts[f"{split}_images"] == 0:
            raise RuntimeError(f"dataset needs a nonempty {split} split: {counts}")
        if counts[f"{split}_labels"] != counts[f"{split}_images"]:
            raise RuntimeError(f"one or more {split} images lack labels: {counts}")
    _check_label_shape(data_yaml)

    os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")
    from ultralytics import YOLO

    device, torch_version = _choose_device(args.device)
    args.project = args.project.expanduser().resolve()
    args.final_weights = args.final_weights.expanduser().resolve()
    args.metrics_out = args.metrics_out.expanduser().resolve()
    args.project.mkdir(parents=True, exist_ok=True)
    args.final_weights.parent.mkdir(parents=True, exist_ok=True)
    args.metrics_out.parent.mkdir(parents=True, exist_ok=True)
    print(f"Dataset: {data_yaml}")
    print(f"Counts: {counts}")
    print(f"Training device: {device} (torch {torch_version})")

    model = YOLO(args.model)
    started = time.monotonic()
    results = model.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        workers=args.workers,
        device=device,
        project=str(args.project),
        name=args.name,
        exist_ok=True,
        resume=args.resume,
        seed=args.seed,
        deterministic=True,
        cache="disk",
        amp=device not in ("mps", "cpu"),
        optimizer="AdamW",
        lr0=0.0015,
        lrf=0.01,
        cos_lr=True,
        patience=args.patience,
        close_mosaic=15,
        box=8.0,
        pose=14.0,
        kobj=2.0,
        cls=0.5,
        dfl=2.0,
        hsv_h=0.02,
        hsv_s=0.65,
        hsv_v=0.45,
        # The old virtual-label dataset had no angle diversity.  The collector
        # now supplies real wrist orientation perturbations; retain modest image
        # augmentation so the result is not tied to one handoff attitude.
        degrees=12.0,
        translate=0.10,
        scale=0.35,
        shear=2.0,
        perspective=0.0002,
        fliplr=0.5,
        flipud=0.0,
        mosaic=0.35,
        mixup=0.0,
        copy_paste=0.0,
        erasing=0.20,
        plots=True,
        verbose=True,
    )
    elapsed = time.monotonic() - started
    run_dir = args.project / args.name
    best_source = run_dir / "weights" / "best.pt"
    if not best_source.is_file():
        raise FileNotFoundError(f"training completed without best.pt: {best_source}")
    shutil.copy2(best_source, args.final_weights)

    metrics = {}
    if hasattr(results, "results_dict"):
        metrics = {key: float(value) for key, value in results.results_dict.items()}
    report = {
        "data": str(data_yaml),
        "dataset_counts": counts,
        "label_convention": "physical_front_mouth_22.407x8.100mm_plus_center",
        "initial_model": args.model,
        "best_source": str(best_source),
        "final_weights": str(args.final_weights),
        "device": device,
        "torch_version": torch_version,
        "epochs_requested": args.epochs,
        "imgsz": args.imgsz,
        "batch": args.batch,
        "elapsed_seconds": elapsed,
        "metrics": metrics,
    }
    args.metrics_out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
